# Generated by Django 3.1.5 on 2021-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210116_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Görsel Adı')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Fotoğraf')),
            ],
        ),
    ]
