# Generated by Django 3.1.5 on 2021-01-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='photo',
        ),
    ]
