# Generated by Django 3.1.5 on 2021-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210122_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/uploads/', verbose_name='Görsel'),
        ),
    ]
