# Generated by Django 3.1.5 on 2021-01-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ürün Adı')),
                ('amount', models.IntegerField(verbose_name='Ürün Adedi')),
                ('price', models.IntegerField(verbose_name='Ürün Fiyatı')),
                ('image', models.ImageField(upload_to='', verbose_name='Ürün Görseli')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
            ],
        ),
    ]
