# Generated by Django 3.1.5 on 2021-01-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210115_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Ürün Görseli'),
        ),
    ]
